# Generated by Django 4.0.3 on 2022-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('password', models.CharField(max_length=15, verbose_name='Password')),
                ('avatar', models.ImageField(default='imagenes/profile_default.png', upload_to='imagenes/', verbose_name='Avatar')),
            ],
        ),
    ]
