# Generated by Django 4.0.3 on 2022-03-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='avatar',
            field=models.ImageField(default='imagenes/profile_default.png', upload_to='login/imagenes/', verbose_name='Avatar'),
        ),
    ]
