# Generated by Django 4.0.3 on 2022-03-05 20:27

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_belnu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agente', models.CharField(default='500-cordoba', max_length=100, null=True, verbose_name='Agente')),
                ('movimiento', models.CharField(max_length=100, verbose_name='Movimiento')),
                ('codigo', models.PositiveIntegerField(verbose_name='Codigo')),
                ('edicion', models.CharField(max_length=50, verbose_name='Edicion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='PVP')),
                ('proveedor', models.CharField(default='la nacion', max_length=100, verbose_name='Proveedor')),
                ('estado', models.CharField(default='pendiente', max_length=100, null=True, verbose_name='Estado')),
                ('doc_ln_asoc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc_LN_Asociados')),
                ('cantidad_ln', models.IntegerField(blank=True, null=True, verbose_name='Cantidad_LN')),
                ('importe_ln', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Importe_LN')),
                ('diferencia_cant', models.IntegerField(blank=True, null=True, verbose_name='Diferencia_Cantidad')),
                ('diferencia_importe', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Diferencia_Importe')),
                ('obs', models.TextField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'DocumentoBelnu',
                'verbose_name_plural': 'DocumentosBelnu',
                'db_table': '',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='doc_Nacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agente', models.CharField(default='500-cordoba', max_length=100, null=True, verbose_name='Agente')),
                ('tipo_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo_Doc')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_vto', models.DateField(verbose_name='Fecha_Vto')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('nro_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc_LN_Asociados')),
                ('movimiento', models.CharField(max_length=100, verbose_name='Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='PVP')),
                ('desc_cadena', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Desc_Cadena')),
                ('recargo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Recargo')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe')),
                ('controlado', models.CharField(default='no', max_length=25, verbose_name='Controlado')),
                ('diferencias', models.CharField(default='no', max_length=25, verbose_name='Diferencias')),
                ('obs', models.TextField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('costo', computed_property.fields.ComputedTextField(compute_from='calc_costo', editable=False, verbose_name='Costo')),
                ('edicion', computed_property.fields.ComputedTextField(blank=True, compute_from='calc_edicion', editable=False, null=True, verbose_name='Edicion')),
                ('codigo', computed_property.fields.ComputedTextField(blank=True, compute_from='calc_codigo', editable=False, null=True, verbose_name='Codigo')),
                ('tipo_pub', computed_property.fields.ComputedTextField(blank=True, compute_from='calc_tipo_pub', editable=False, null=True, verbose_name='Tipo_Publicacion')),
            ],
            options={
                'verbose_name': 'DocumentoLN',
                'verbose_name_plural': 'DocumentosLN',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExcelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
            ],
        ),
    ]
