# Generated by Django 4.0.3 on 2022-03-07 18:00

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha:')),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=30, verbose_name='Turno:')),
                ('chofer', models.CharField(max_length=60, verbose_name='Chofer:')),
                ('movil', models.CharField(max_length=30, verbose_name='Movil:')),
                ('acomp', models.CharField(max_length=60, verbose_name='Acompañante:')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo Viaje:')),
                ('cant_viajes', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Viajes:')),
                ('cant_acomp', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Acompañantes:')),
                ('cant_paquetes', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Paquetes:')),
                ('tarifa_camion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Camion:')),
                ('tarifa_acomp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Acompañante:')),
                ('obs', models.TextField(max_length=500, verbose_name='Observaciones:')),
                ('importe', computed_property.fields.ComputedTextField(blank=True, compute_from='_importe', editable=False, null=True, verbose_name='Importe:')),
                ('imp_final', computed_property.fields.ComputedTextField(blank=True, compute_from='_imp_final', editable=False, null=True, verbose_name='Importe Final:')),
            ],
            options={
                'verbose_name': 'Hop',
                'verbose_name_plural': 'Hops',
                'db_table': '',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
    ]
