# Generated by Django 4.0.3 on 2022-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0002_alter_hop_acomp_alter_hop_obs_alter_hop_tarifa_acomp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre:')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido:')),
                ('puesto', models.CharField(choices=[('Chofer', 'Chofer'), ('Acompañante', 'Acompañante')], max_length=60, verbose_name='Puesto:')),
            ],
        ),
        migrations.AlterField(
            model_name='hop',
            name='cant_acomp',
            field=models.PositiveIntegerField(default='0', verbose_name='Cantidad de Acompañantes:'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='cant_paquetes',
            field=models.PositiveIntegerField(default='0', verbose_name='Cantidad de Paquetes:'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='cant_viajes',
            field=models.PositiveIntegerField(default='1', verbose_name='Cantidad de Viajes:'),
        ),
    ]
