# Generated by Django 4.0.3 on 2022-03-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0004_tipo_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_viaje',
            name='tipo',
            field=models.CharField(choices=[('Camion Drop Off', 'Camion Drop Off'), ('Sprinter Drop Off', 'Sprinter Drop Off'), ('Sprinter Pick Up', 'Sprinter Pick Up')], max_length=60, unique=True, verbose_name='Tipo de Viaje:'),
        ),
    ]
