# Generated by Django 4.0.3 on 2022-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0006_alter_hop_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='tipo',
            field=models.CharField(choices=[('Camion Drop Off', 'Camion Drop Off'), ('Sprinter Drop Off', 'Sprinter Drop Off'), ('Sprinter Pick Up', 'Sprinter Pick Up')], default=2, max_length=30, verbose_name='Tipo Viaje:'),
            preserve_default=False,
        ),
    ]
