# Generated by Django 4.0.3 on 2022-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0007_alter_hop_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Movil:')),
            ],
        ),
        migrations.AlterField(
            model_name='tipo_viaje',
            name='tipo',
            field=models.CharField(max_length=60, unique=True, verbose_name='Tipo de Viaje:'),
        ),
    ]
