# Generated by Django 4.0.3 on 2022-03-08 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0008_moviles_alter_tipo_viaje_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviles',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='moviles',
            name='patente',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Patente:'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='ruta',
            field=models.DateField(auto_now=True, verbose_name='Ruta Hasta:'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='tipo',
            field=models.CharField(choices=[('Sprinter', 'Sprinter'), ('Camion', 'Camion')], default=django.utils.timezone.now, max_length=60, verbose_name='Tipo de Movil:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviles',
            name='vtv',
            field=models.DateField(auto_now=True, verbose_name='VTV Hasta:'),
        ),
    ]
