# Generated by Django 4.0.3 on 2022-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0009_rename_numero_moviles_numero_moviles_patente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='ruta',
            field=models.DateField(blank=True, null=True, verbose_name='Ruta Hasta:'),
        ),
        migrations.AlterField(
            model_name='moviles',
            name='vtv',
            field=models.DateField(blank=True, null=True, verbose_name='VTV Hasta:'),
        ),
    ]
