# Generated by Django 4.0.3 on 2022-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hop', '0010_alter_moviles_ruta_alter_moviles_vtv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
